dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "B9oBJzfxPoE4rfMp29eJ0UswCMnECq6CY/oDuGf0rdkI98xKxbZxSiWhJ1wvh6FLU6bLq20S9hg/SbGvGwtKFULErt4HQapkLBxxBQp4zZwGs6YG9+vpsBccyQwNhBp/Jngp9+jj+n0NqMXRUYwBw
VC25FF4Zlj54W6C6Lu0fwfwTdc9EVjxBuhHb3fdJhhzAnxm45o8woPzGOmARhPzR3PtVFCpI+z8XYtD1CTklIEGPUP5N2qVX6riLEeumFm9uZYCh6fyjxYSg2veCZ6d1gkGt55kV4LvlSU2igBdM3VDt82Y9z63j
7WiWd80m4VPybJtJcjvDrmqEqFW3n4iDWHOmtAh9BMrn6Y8JzaqQRj1/7IK1PLQZepbwChzYvlPk6t4bqGo9a2u05+pOOB7BGrForL6epPLWLcwJjPOzBmp14AHjnIk3w9idY20NXkKNzGCzD7JwAIGPkaNK0kuL
5IDAanl+jnYtJDK5YSWxY2od6g/ki3rhwwxvjHn1uOILtXO8+4m1+OJKH8umSvNVprjZtvTx+DXvVlXw4wcS+2USu4ujA4T5XF2SfnNdkBZCUDF5E6cfIodadS67D/K41HhP8481uskzpXaOggdMkyktraaPN5sw
yYpW88AMHxXb+WzTOoN2g5ZkfNZcgo+OR3lqjjCaF7atbp8POWLT4Y="

addons:
  # Required to avoid openjdk7 buffer overflow:
  # https://github.com/travis-ci/travis-ci/issues/5227
  hosts:
    - myshorthost
  hostname: myshorthost

before_install:
  - sudo apt-get -qq update
  # This package is needed by the jaxwscommons-81 IT (see Github issue #18)
  - sudo apt-get install -y gsettings-desktop-schemas

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "mvn --show-version --errors --batch-mode validate dependency:go-offline"

script: 
#  - "mvn --show-version --errors --batch-mode -Prun-its clean verify -Dittest.debug=false -Dinvoker.streamLogs=true"
  - "mvn --show-version --errors --batch-mode clean verify -Dittest.debug=false -Dinvoker.streamLogs=true"

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - stage: test
      jdk: openjdk11
    - stage: test
      jdk: openjdk12
